### ISSUE TITLE
Provide running project for asp.net core

### ISSUE THREAD

**Issue by itsat** [nreco/data#18]
I am getting lots of error after downloading sample project from github. What to do now?.

**Comment by VitaliyMF** [comment]
@itsat I've just checked examples and it seems they work correctly. Could you provide any details on the errors?.. Are you trying to build them from VS2015, or with command line (dotnet build) ?

**Comment by itsat** [comment]
Yes, I am using VS2015.

Errors are 

The type or namespace name 'QVar' could not be found (are you missing a using directive or an assembly reference?)

The type or namespace name 'Query' could not be found (are you missing a using directive or an assembly reference?)

The type or namespace name 'QSort' could not be found (are you missing a using directive or an assembly reference?)

..

**Comment by VitaliyMF** [comment]
I guess you're trying to build NReco.Data.Tests; please use cli ( "dotnet" commands) instead:

```
dotnet restore
dotnet build (or "dotnet test" for NReco.Data.Tests) 
```

VS2015 still has some issues related to .NET Core projects and one of them that it cannot handle correctly reference to netstandard-compatible PCL project type (this is NReco.Data itself).  

Examples should work fine from VS2015 as they reference NReco.Data nuget package instead of project file.

**Comment by itsat** [comment]
Now, It's working but what about datasource. I mean in ADO.Net we provide 
Data Source="Server=ABC\\SQL12;Database=SNew;Integrated Security=true;MultipleActiveResultSets=true"
but in your solution you have provided physical path of 'northwind.db' so, How can i manage sql connection

**Comment by VitaliyMF** [comment]
@itsat examples use SQLite database for the sake of simplicity.

For MS SQL Server you need to use SqlClient instead of SQLite connector, for example:

```
var dbFactory = new DbFactory(System.Data.SqlClient.SqlClientFactory.Instance) {
    LastInsertIdSelectText = "SELECT @@IDENTITY"
};
```

**Comment by itsat** [comment]
So, I have to change project reference also

"Microsoft.Data.SQLite >= 1.0.0" will be replaced  by "System.Data.SqlClient": "4.1.0" .

**Comment by VitaliyMF** [comment]
@itsat that's correct. And use SqlClient factory instance as parameter for NReco.Data.DbFactory class. "LastInsertIdSelectText" property should be initialized only if you want to get back autogenerated ids.

**Comment by itsat** [comment]
Ok. So, what about the DataTable and DataSet in NReco

**Comment by VitaliyMF** [comment]
@itsat 
DataSet/DataTable/DataRow are not available in netstandard1.6, but it seems these classes will back in netstandard2.0. I'll add support for DataTable/DataRow as soon as this comes true.

For now NReco.Data implements lightweight structure called [RecordSet](https://github.com/nreco/data/wiki/RecordSet) and supplementary classes (like RecordSetReader). It acts almost like DataTable (for example, it can be used for passing Table-Valued Parameters to stored procedures).

Note that because of its simplicity, RecordSet is very efficient (ToRecordSet works almost with the same performance as Dapper's mapping).

**Comment by VitaliyMF** [comment]
Support of DataSet/DataTable for netstandard2.0 will be added in https://github.com/nreco/data/issues/26, 
working asp.net mvc core example is provided in https://github.com/nreco/data/issues/21
