### ISSUE TITLE
Relex Parser Spaces in Names

### ISSUE THREAD

**Issue by antonbeukes** [nreco/data#19]
How can someone use escape spaces in column names. 
For Example 
`string relex = @"Users([user id]=100:int)[[name],[last name]]";
            var relexParser = new NReco.Data.Relex.RelexParser();
            var query = relexParser.Parse(relex);`

returns 
An unhandled exception of type 'NReco.Data.Relex.RelexParseException' occurred in NReco.Data.dll
Additional information: Invalid syntax (position: 7, expression: Users([user id]=100:int)[[name],[last name]])

**Comment by VitaliyMF** [comment]
@antonbeukes currently relex parser doesn't support names in brackets like [user id]. You can specify column names with spaces in the following way:

`string relex = @"Users(""[user id]"":sql=""100"":int)[name,\"last name\"]";`

This query will lead to correct SQL query, but Query structure will contain QRawSql node for "[user id]" instead of QField. 
I think it is good idea to introduce one more special marker for string constants that will force QField node type, like "[user id]":field -- will do that

**Comment by VitaliyMF** [comment]
Added support of delimited identifiers (table names and column names), for example:
`"Purchase Orders":table("PO Number":field = "1111")[*]`

+ improved SQL-generation components to support db-dependent formatting of delimited identifiers #20

**Comment by antonbeukes** [comment]
Thanks.
