### ISSUE TITLE
GraphQL API example: auto-generated schema by SQL database

### ISSUE THREAD

**Issue by MakaBuka** [nreco/data#22]
Hi guys,

Let's try to implement GraphQL.Net based on NReco.Data (I'm talking about this project - https://github.com/graphql-dotnet/graphql-dotnet )
So, here's my vision:

- add one API endpoint (let's call it - graphql)
- try to implement graphql.net based on NReco.Data (just simple 1-level queries)

Thx, D.

**Comment by VitaliyMF** [comment]
+1 this is good illustration for NReco.Data benefits because both performance and ability to compose queries dynamically are critical for GraphQL-based API.

Lets use SQLite [northwind](https://github.com/nreco/data/blob/master/examples/SqliteDemo.WebApi/northwind.db) database for the sake of simplicity.

**Comment by VitaliyMF** [comment]
This example may be useful in scenarios when GraphQL schema may be automatically generated by database or POCO models, here is the questions from https://github.com/graphql-dotnet project:

- https://github.com/graphql-dotnet/graphql-dotnet/issues/132
- https://github.com/graphql-dotnet/graphql-dotnet/issues/196
- https://github.com/graphql-dotnet/graphql-dotnet/issues/255

**Comment by VitaliyMF** [comment]
Done by @MakaBuka .
This example illustrates how GraphQL queries may be processed automatically by DB schema (SQLite in our case). It cannot handle mutations and sub-collections; these features may be added on demand.
