### ISSUE TITLE
Missing type in NReco.Data Latest Stable 1.1.1

### ISSUE THREAD

**Issue by xavidram** [nreco/data#59]
Upon working on a new project, I added the latest NReco.Data stable packages along with the latest NReco.GraphQL package. When executing a GraphQL query, the exception response is as follows:

![image](https://user-images.githubusercontent.com/1348719/82481772-6f87ca80-9a9b-11ea-8004-17b97f9d38d7.png)

I am able to fix this issue by downgrading the NReco.Data package to version 1.0.6 which seems to have the NReco.Data.ListSortDirection assembly in the package. The Version 1.1.1 does not seem to have it included.

My project is working fine with NReco.Data version 1.0.6, but I just wanted to mention the missing assembly in the latest stable version.

**Comment by VitaliyMF** [comment]
@xavidram there was a breaking change in 1.1.0 related to ListSortDirection (see notes here https://www.nuget.org/packages/NReco.Data/).

In short, there was own enum NReco.Data.ListSortDirection because in early .NET Core 1.x days type System.ComponentModel.ListSortDirection was missed. However, in netstandard20 it is available, and .NET Core 1.x is not used any more. So in version 1.1.0 own enum was removed to avoid any possible ambiguity.

All this means that you cannot upgrade NReco.Data to 1.1.0 if you use existing release of NReco.Graphql because of this breaking change. In upcoming release of NReco.Graphql reference to NReco.Data will be upgraded to 1.1.1.

**Comment by xavidram** [comment]
That makes sense. I should have read the changelog.  If it is not too much of an bother. Could you give me an insight as to how the NrecoGraphQL is querying Relex subqueries? 

I have two Tables as follows:

Employee (ID int, DivisionID int, ....)
Division(ID int, Name varchar(50), ...)

the Schema object for employees is as follows:
![image](https://user-images.githubusercontent.com/1348719/82485427-04d98d80-9aa1-11ea-8879-cc2d01d75b24.png)

And Division Schema object is as follows:
![image](https://user-images.githubusercontent.com/1348719/82485478-1ae74e00-9aa1-11ea-92f9-cca45e5d8fd2.png)


The Relex string's on the Employee Schema seem correct from what I have seen in the documentation. But oddly enough, for any query that calls a Relex query, it always returns the last item in the table

![image](https://user-images.githubusercontent.com/1348719/82485640-5da92600-9aa1-11ea-9181-72b863d27d6a.png)

Is there a fallback that the Relex query executor could fall back to that would cause it to grab the last item in the table?

**Comment by MakaBuka** [comment]
@xavidram 
It's related to commercial component NReco.GraphQL, so, check you email box - I've sent workaround.
